os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

cache:
    apt: true

env:
  global:
    - TRAVIS_CI=true
    - secure: "b26IeXTqR4K5jWoYqupt/d9j4ri6IvDwjVmO6PNGWn6zIZBsjfvnH5ctkFvWb00Agl5F0FG7oRsmHePbdVMa0B0Py3/uPl1osHzoayqw3rwAF54BICP0IUzWsL1O459KEfh+urWUM3/mr7BRwOLPnlMIE82VnkGqeW2KgQqR0Aw="
    - BINTRAY_TOKEN=${BINTRAY_TOKEN}

before_install:
  - echo $TRAVIS_OS_NAME
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq

install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq gnulib dh-make; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libwxgtk2.8-dev libxml2-dev libssl-dev debhelper autotools-dev automake gnupg lintian fakeroot pbuilder cdbs gnome-pkg-tools libwxsqlite3-2.8-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install gnu-sed wxmac; fi

before_script:
  - echo $TRAVIS_OS_NAME
  - autoreconf -i -I/usr/share/gnulib/m4 -I `pwd`/m4

script:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./configure && make -j2 package-deb-local; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./configure && make && make osx-make-bin package-osx-intel64-dmg; fi

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - if [ "$TRAVIS_OS_NAME" == "osx" -o "$CXX" == "clang++" ]; then cd misc && ./upload_bintray.sh; fi
