language: cpp
os:
  - linux
  - osx
compiler:
  #- gcc
  - clang
matrix:
  exclude:
    - os: osx
      compiler: gcc # Don't do a gcc build on OSX
cache: apt
env:
  global:
    - TRAVIS_CI=true
    - secure: "W7++isBzG0Lsq3ktAIVA4FZ5O2Hn1JptWNBjDlDrxdUxM/g5HP0R8qxC58HRVEjWI9vCU7YgcsmxPhuSNdgFYhn84p4dcwU5N8PlTfz4HfpbARUu5PYlO8l8Qeag/PutDTTai2bJAhRruNvgP1NEz9Oq/KG6aHHNcVxZjP2iSo8="
    - BINTRAY_TOKEN=${BINTRAY_TOKEN}

before_install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX=clang++ && CC=clang && sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi

install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq gnulib dh-make; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libwxgtk2.8-dev libxml2-dev uuid-dev debhelper autotools-dev automake gnupg lintian fakeroot pbuilder cdbs libwxsqlite3*-dev libsqlite3*-dev basename; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gsed automake autoconf libtool wxmac; fi

before_script:
  - echo $TRAVIS_OS_NAME
  - autoreconf -i -I/usr/share/gnulib/m4 -I `pwd`/m4

script:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./configure && make -j2 package-deb-local; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./configure && make -j2 osx-make-bin; fi

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - cd misc && ./upload_bintray.sh
